### ISSUE TITLE
addons don't install correctly

### ISSUE THREAD

**Issue by saruye** [weaveworks/kubernetes-anywhere#79]
hi, 
I followed the instructions to setup a kubernetes cluster on three servers. Everything is working fine until I start installing the addons.yml. 
The command goes through and I get the output: 
`namespace "kube-system" created
replicationcontroller "kube-dns-v11" created
service "kube-dns" created`

When running `kubectl get rc` afterwards I get no result though. When running `kubectl get svc` I get: 
```
[root@10f10d7c3750 resources]# kubectl get svc
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   10.16.0.1    <none>        443/TCP   29m
```

I think the services are not created properly. It seems like this is related to the sky-dns container not starting correctly. The container `k8s_kube2sky....` is not starting correctly. When running `docker logs` on this container I get (many entries of): 
`I0508 19:41:50.565989       1 kube2sky.go:604] Ignoring error while waiting for service default/kubernetes: yaml: mapping values are not allowed in this context. Sleeping 1s before retrying`

I just started with playing with kubernetes and don't know how to debug this any further. I found that somebody had the same issue here: https://github.com/kubernetes/kubernetes/issues/23111 
Reading this sounds like it is an issue with authorization and secrets being wrong. I didn't do anything in this regard. And running kubectl get secrets returns nothing. 
Am I doing something wrong? I thought with this setup everything should be taken care of automatically. 

I appreciate any help!
arne

**Comment by errordeveloper** [comment]
Thank you for reporting this. It'd help if you could specify whether you have use PKI, or not. The `kube-dns` service is in `kube-system` namespace (check `kubectl get svc kube-dns --namespace=kube-system`).

**Comment by saruye** [comment]
hi. 
thanks for the response!
I didn't use pki yet. I thought it was optional I just wanted to start with something simple first. When running the command I get: 
`[root@a42e1ac7578a resources]# kubectl get svc kube-dns --namespace=kube-system
NAME       CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
kube-dns   10.16.0.3    <none>        53/UDP,53/TCP   18h`

the replication controller is also there: 
`[root@a42e1ac7578a resources]# kubectl get rc --namespace=kube-system
NAME           DESIRED   CURRENT   AGE
kube-dns-v11   1         1         18h`

I wanted to install the dashboard as instructed here: http://kubernetes.io/docs/user-guide/ui-access/

**Comment by errordeveloper** [comment]
The main problem with addons is that most of them depend on service accounts, and service accounts don't work without PKI. I should probably document this a bit more explicitly.

**Comment by saruye** [comment]
thanks @errordeveloper I'll try to run everything with pki later tonight. Will let you know how it goes.

**Comment by errordeveloper** [comment]
Also, I've just noticed that the toplevel readme doesn't mention `addons-no-pki.yaml`, which what you need to use for non-PKI setup. That manifests is slightly different from `addons.yaml`, it just specifies API server URL instead of relying on service accounts. I'll make sure to add it to the docs now.

**Comment by errordeveloper** [comment]
@saruye I've updated the docs, please feel free to reopen the issue, if it doesn't work.

**Comment by saruye** [comment]
hi @errordeveloper I tried to install the addons with non-pki addons, but still had the same error that kube2sky couldn't start correctly. I tried the addons for all versions. With version 1.1 I didn't see the error in the logs.The container was recreated always. So there was an error anyway. 

I did set up a cluster with pki now which seems to work fine. One problem I had though was: The api is listening on port 8080. When installing the addons the skydns also listens on port 8080. Since I didn't specify the external port ( not really sure how to do that), the containers are mapped on any hosts. even on the kube-apiserver. When connecting on port 8080 I got to the webinterface of the dns container. Something about health check. 

I tried connecting on port 6443 to get to the api (and finally the ui), but I was asked for username/password. Where do I get this from? Can you lead me to some documentation about this? How do I get the certificate that is used for serving the api?

Hope my questions are not too stupid ... 

Regards, 
arne
