### ISSUE TITLE
Resuming on a laptop running docker-machine logs errors

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/kubernetes-anywhere#87]
After sleeping for a while and resuming the terminal on the docker-machine box gets spammed with:

`Error attempting heartbeat call to plugin server: connection is shut down`

I can't really tell which process is logging this, so not sure if it is kubernetes, or kubernetes-anywhere...

**Comment by errordeveloper** [comment]
This a Docker Machine error message.
