### ISSUE TITLE
/var/log/containers not present in the host, which breaks the fluentd add ons

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/kubernetes-anywhere#90]
The kubernetes fluentd add-ons rely on kubelet creating /var/log/containers in the host in order to mount them it in the container and parse the containing logs. See https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/td-agent.conf#L2-L6

However, the containerized kubelet in k8s-anywhere only creates /var/log/containers locally, not getting exposed to the host and in turn not propagated to the fluentd add-on.

**Comment by errordeveloper** [comment]
So does kubelete duplicate logs into that directory? I understand why, but it's rather very redundant. Fixing this should be the matter of adding a line to [`setup-kubelet-volumes`](https://github.com/weaveworks/kubernetes-anywhere/blob/master/docker-images/toolbox/scripts/setup-kubelet-volumes).

**Comment by errordeveloper** [comment]
> So does kubelete duplicate logs into that directory? I understand why, but it's rather very redundant.

Ok, I thought it'd duplicate logs in order to support any runtime... So, it just creates symlinks there, which is sensible.
